### PR TITLE
Implemented TriggerAU's suggested fix to range limit

### LINKED ISSUE #2531: Wrong conversion for PartModuleField values using Robotic Parts
Trying to set the PartModuleFields for the DLCs robotic parts (ie. Target Angle), causes values to be clamped between 0 and 100 and rounded to the nearest integer. This is wrong for most sliders in the new DLC.

Cause of the issue seems to be https://github.com/KSP-KOS/KOS/blob/d6258fad1c4a35e2fa3b885e3fc0879b9c140ca3/src/kOS/Suffixed/PartModuleField/PartModuleFields.cs#L174

`UI_FloatRange` claims that its range is always 0 to 100 with a step-size of 1.

Ignoring the clamp entirely seem to fix the issue and still cause values to be properly converted to the UIs possible values, maybe Squad moved the logic from the UI to the actual API, causing this step to be unnecessary on kOSs side?

### PR DESCRIPTION
**Pull request by Dunbaratu**
Fixes #2531

I got some feedback from SQUAD team member TriggerAU about this problem and he pointed me to the API call that SQUAD uses to obtain the float ranges, and it encapsulates some of the work needed to find the cases where a float range is getting overridden by another float range.  This method call TryGetFieldUIControl seems to do everything right and obtain the true ranges that game is actually using.

### CODE REVIEW

File: src/kOS/Suffixed/PartModuleField/PartModuleFields.cs [hunk 1]
```diff
@@ -133,49 +122,40 @@ private bool IsLegalValue(BaseField field, ref Structure newVal, out KOSExceptio
...
+            var vector2 = control as UI_Vector2;
+            if (vector2 != null)
+            {
+                // I have no clue what this actually looks like in the UI?  What is a
+                // user editable 2-D vector widget?  I've never seen this before.
+                if (convertedVal != null)
                 {
-                    // I have no clue what this actually looks like in the UI?  What is a
-                    // user editable 2-D vector widget?  I've never seen this before.
-                    if (convertedVal != null)
```
Comment (Dunbaratu) [inline src/kOS/Suffixed/PartModuleField/PartModuleFields.cs]: The above looks like a large edit, but if you look carefully, all it is is just a change of indent level.
