### PR TITLE
Fixes #1860 - progress bar terminal resize

### LINKED ISSUE #1860: Signal delay progress bar ignores terminal resize - draws in the wrong spot.
This has always annoyed me a little and I think I saw the cause of it.

In RemoteTechInterpreter.cs (which is about to become renamed to ConnectivityInterpreter.cs as part of PR #1850 , which will probably be merged in before this issue is resolved, so look for it there), we have these lines:

```
        private void CreateProgressBarSubBuffer()
        {
            progressBarSubBuffer = new SubBuffer();
            progressBarSubBuffer.SetSize(3, ColumnCount);
            progressBarSubBuffer.Fixed = true;
            progressBarSubBuffer.PositionRow = RowCount - progressBarSubBuffer.RowCount;
            AddSubBuffer(progressBarSubBuffer);

            var separator = new string('-', progressBarSubBuffer.ColumnCount);
            progressBarSubBuffer.Buffer[0].ArrayCopyFrom(separator.ToCharArray(), 0, 0);
        }
```
These measurements like RowCount and ColumnCount are only queried when the Interpreter was first constructed, and then they get stuck that way for the life of the interpreter.  If you stretch or shrink the window, then all the progress bars being drawn for signal delay get messed up because it never reassigns these values for `progressBarSubBuffer` to match the new size.

### PR DESCRIPTION
**Pull request by Dunbaratu**
Fixes #1860 

To test:

  - Be sure RemoteTech is installed.
  - Start new sandbox game.  Choose RemoteTechConnectivityManager.
  - Use Alt-F12 'set orbit' cheat to put a comsat into Kerbin orbit
  that can act as a relay to Duna.
  - Use Alt-F12 'set orbit' cheat to put a kOS-capable probe around Duna that
  relays through the satellite you made above.
  - Keep trying ``print "hello".`` in the probe's kOS Terminal,
  after resizing the terminal to different amounts.  Notice it will
  react to changes to the terminal made during the progres bar's
  wait time too, re-drawing the bar to fit the new size at the same
  ratio of completion it had before.

### CODE REVIEW

File: src/kOS/Screen/ConnectivityInterpreter.cs [hunk 1]
```diff
@@ -23,19 +23,32 @@ public class ConnectivityInterpreter : Interpreter, IUpdateObserver
...
+            CreateProgressBarSubBuffer(this);
+            AddResizeNotifier(CreateProgressBarSubBuffer);
         }
 
-        private void CreateProgressBarSubBuffer()
+        ~ConnectivityInterpreter()
         {
-            progressBarSubBuffer = new SubBuffer();
+            RemoveResizeNotifier(CreateProgressBarSubBuffer);
+        }
```
Comment (Dunbaratu) [inline src/kOS/Screen/ConnectivityInterpreter.cs]: I just realized this won't work.  The destructor never gets called until after you orphan this instance.  This instance can't orphan until after you call ``RemoveResizeNotifier()``, so this can never actually get called.  This has to be moved elsewhere in the logic, not in the destructor.

Comment (Dunbaratu) [inline src/kOS/Screen/ConnectivityInterpreter.cs]: Addendum: Okay, actually it probably did work all along.  I put it back, with the explanatory comment about why it probably was fine all along.  But even so, I still added the hook removal to SharedObjects's Destroy work just to be explicit about it.  Now there's two spots that can both catch this and do the job.
